# Generated by Django 4.2.16 on 2025-09-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recipe_id', models.IntegerField(unique=True)),
                ('minutes', models.IntegerField()),
                ('contributor_id', models.IntegerField()),
                ('submitted', models.DateField()),
                ('tags', models.TextField()),
                ('nutrition', models.TextField()),
                ('n_steps', models.IntegerField()),
                ('steps', models.TextField()),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('n_ingredients', models.IntegerField()),
            ],
        ),
    ]
